/**
 * AUTO-GENERATED by scripts/generate-icon-map.ts — do not edit by hand.
 * Regenerated on every `npm run build` (prebuild) from content YAML icon: values.
 * Icons: 76
 */
import type { ComponentType } from "react";

export type LucideIconComponent = ComponentType<{
  className?: string;
  size?: number | string;
  width?: string;
  height?: string;
  color?: string;
  style?: React.CSSProperties;
}>;

export type LucideIconLoader = () => Promise<{ default: LucideIconComponent }>;

/** Kebab-case Lucide slug → per-icon dynamic import (Vite code-splits each). */
export const curatedLucideImports: Record<string, LucideIconLoader> = {
  "arrow-right": () => import("lucide-react/dist/esm/icons/arrow-right.js"),
  "award": () => import("lucide-react/dist/esm/icons/award.js"),
  "bar-chart-2": () => import("lucide-react/dist/esm/icons/bar-chart-2.js"),
  "bolt": () => import("lucide-react/dist/esm/icons/bolt.js"),
  "book": () => import("lucide-react/dist/esm/icons/book.js"),
  "book-open": () => import("lucide-react/dist/esm/icons/book-open.js"),
  "bot": () => import("lucide-react/dist/esm/icons/bot.js"),
  "bot-message-square": () => import("lucide-react/dist/esm/icons/bot-message-square.js"),
  "brain": () => import("lucide-react/dist/esm/icons/brain.js"),
  "briefcase-business": () => import("lucide-react/dist/esm/icons/briefcase-business.js"),
  "bug": () => import("lucide-react/dist/esm/icons/bug.js"),
  "building": () => import("lucide-react/dist/esm/icons/building.js"),
  "calculator": () => import("lucide-react/dist/esm/icons/calculator.js"),
  "calendar": () => import("lucide-react/dist/esm/icons/calendar.js"),
  "chart-bar": () => import("lucide-react/dist/esm/icons/chart-bar.js"),
  "chart-line": () => import("lucide-react/dist/esm/icons/chart-line.js"),
  "chart-no-axes-combined": () => import("lucide-react/dist/esm/icons/chart-no-axes-combined.js"),
  "check": () => import("lucide-react/dist/esm/icons/check.js"),
  "chevron-down": () => import("lucide-react/dist/esm/icons/chevron-down.js"),
  "chevron-left": () => import("lucide-react/dist/esm/icons/chevron-left.js"),
  "chevron-right": () => import("lucide-react/dist/esm/icons/chevron-right.js"),
  "circle-dollar-sign": () => import("lucide-react/dist/esm/icons/circle-dollar-sign.js"),
  "clipboard-check": () => import("lucide-react/dist/esm/icons/clipboard-check.js"),
  "clock": () => import("lucide-react/dist/esm/icons/clock.js"),
  "code": () => import("lucide-react/dist/esm/icons/code.js"),
  "code-xml": () => import("lucide-react/dist/esm/icons/code-xml.js"),
  "compass": () => import("lucide-react/dist/esm/icons/compass.js"),
  "cpu": () => import("lucide-react/dist/esm/icons/cpu.js"),
  "credit-card": () => import("lucide-react/dist/esm/icons/credit-card.js"),
  "database": () => import("lucide-react/dist/esm/icons/database.js"),
  "dollar-sign": () => import("lucide-react/dist/esm/icons/dollar-sign.js"),
  "download": () => import("lucide-react/dist/esm/icons/download.js"),
  "dumbbell": () => import("lucide-react/dist/esm/icons/dumbbell.js"),
  "facebook": () => import("lucide-react/dist/esm/icons/facebook.js"),
  "file-text": () => import("lucide-react/dist/esm/icons/file-text.js"),
  "gift": () => import("lucide-react/dist/esm/icons/gift.js"),
  "github": () => import("lucide-react/dist/esm/icons/github.js"),
  "globe": () => import("lucide-react/dist/esm/icons/globe.js"),
  "graduation-cap": () => import("lucide-react/dist/esm/icons/graduation-cap.js"),
  "headset": () => import("lucide-react/dist/esm/icons/headset.js"),
  "instagram": () => import("lucide-react/dist/esm/icons/instagram.js"),
  "kanban": () => import("lucide-react/dist/esm/icons/kanban.js"),
  "key-round": () => import("lucide-react/dist/esm/icons/key-round.js"),
  "layers": () => import("lucide-react/dist/esm/icons/layers.js"),
  "line-chart": () => import("lucide-react/dist/esm/icons/line-chart.js"),
  "link": () => import("lucide-react/dist/esm/icons/link.js"),
  "linkedin": () => import("lucide-react/dist/esm/icons/linkedin.js"),
  "list-ordered": () => import("lucide-react/dist/esm/icons/list-ordered.js"),
  "lock": () => import("lucide-react/dist/esm/icons/lock.js"),
  "lock-open": () => import("lucide-react/dist/esm/icons/lock-open.js"),
  "mail": () => import("lucide-react/dist/esm/icons/mail.js"),
  "medal": () => import("lucide-react/dist/esm/icons/medal.js"),
  "monitor-check": () => import("lucide-react/dist/esm/icons/monitor-check.js"),
  "network": () => import("lucide-react/dist/esm/icons/network.js"),
  "notebook-pen": () => import("lucide-react/dist/esm/icons/notebook-pen.js"),
  "presentation": () => import("lucide-react/dist/esm/icons/presentation.js"),
  "puzzle": () => import("lucide-react/dist/esm/icons/puzzle.js"),
  "repeat": () => import("lucide-react/dist/esm/icons/repeat.js"),
  "search": () => import("lucide-react/dist/esm/icons/search.js"),
  "send": () => import("lucide-react/dist/esm/icons/send.js"),
  "server": () => import("lucide-react/dist/esm/icons/server.js"),
  "settings-2": () => import("lucide-react/dist/esm/icons/settings-2.js"),
  "share": () => import("lucide-react/dist/esm/icons/share.js"),
  "shield": () => import("lucide-react/dist/esm/icons/shield.js"),
  "shield-check": () => import("lucide-react/dist/esm/icons/shield-check.js"),
  "sigma": () => import("lucide-react/dist/esm/icons/sigma.js"),
  "sparkles": () => import("lucide-react/dist/esm/icons/sparkles.js"),
  "star": () => import("lucide-react/dist/esm/icons/star.js"),
  "terminal": () => import("lucide-react/dist/esm/icons/terminal.js"),
  "trending-up": () => import("lucide-react/dist/esm/icons/trending-up.js"),
  "trophy": () => import("lucide-react/dist/esm/icons/trophy.js"),
  "user": () => import("lucide-react/dist/esm/icons/user.js"),
  "users": () => import("lucide-react/dist/esm/icons/users.js"),
  "webhook": () => import("lucide-react/dist/esm/icons/webhook.js"),
  "wrench": () => import("lucide-react/dist/esm/icons/wrench.js"),
  "zap": () => import("lucide-react/dist/esm/icons/zap.js"),
};
