import fs from "fs";
import path from "path";

export function ensureEnvFile(projectRoot: string, extras: Record<string, string> = {}): void {
  const envPath = path.join(projectRoot, ".env");
  const existing = fs.existsSync(envPath) ? fs.readFileSync(envPath, "utf-8") : "";
  const lines: string[] = [];

  if (!/^SESSION_SECRET=/m.test(existing)) {
    const secret = extras.SESSION_SECRET ?? randomSecret();
    lines.push(`SESSION_SECRET=${secret}`);
  }
  if (!/^MCP_SERVER_SECRET=/m.test(existing) && !extras.MCP_SERVER_SECRET) {
    lines.push(`MCP_SERVER_SECRET=${randomSecret()}`);
  }
  // Prefer 5050 so macOS AirPlay (Control Center on :5000) does not steal the URL.
  if (!/^PORT=/m.test(existing) && extras.PORT === undefined) {
    lines.push("PORT=5050");
  }
  for (const [k, v] of Object.entries(extras)) {
    if (k === "SESSION_SECRET" && /^SESSION_SECRET=/m.test(existing)) continue;
    if (new RegExp(`^${k}=`, "m").test(existing)) continue;
    lines.push(`${k}=${v}`);
  }

  if (lines.length === 0 && existing) return;
  const block = (existing && !existing.endsWith("\n") ? "\n" : "") + lines.join("\n") + (lines.length ? "\n" : "");
  if (!existing) {
    fs.writeFileSync(envPath, `# Generated by weblify\n${lines.join("\n")}\n`);
  } else if (lines.length) {
    fs.appendFileSync(envPath, block);
  }
}

export function appendEnvVar(projectRoot: string, key: string, value: string): void {
  const envPath = path.join(projectRoot, ".env");
  const existing = fs.existsSync(envPath) ? fs.readFileSync(envPath, "utf-8") : "";
  const re = new RegExp(`^${key}=.*$`, "m");
  if (re.test(existing)) {
    fs.writeFileSync(envPath, existing.replace(re, `${key}=${value}`));
  } else {
    const prefix = existing && !existing.endsWith("\n") ? "\n" : "";
    fs.appendFileSync(envPath, `${prefix}${key}=${value}\n`);
  }
}

export function readEnvFile(projectRoot: string): Record<string, string> {
  const envPath = path.join(projectRoot, ".env");
  if (!fs.existsSync(envPath)) return {};
  const out: Record<string, string> = {};
  for (const line of fs.readFileSync(envPath, "utf-8").split("\n")) {
    const m = line.match(/^([A-Za-z_][A-Za-z0-9_]*)=(.*)$/);
    if (m) out[m[1]] = m[2];
  }
  return out;
}

function randomSecret(): string {
  return Buffer.from(
    Array.from({ length: 32 }, () => Math.floor(Math.random() * 256)),
  ).toString("base64url");
}
