import { registerJobClass } from "./queue";
import { IndexRefreshJob } from "./definitions/index-refresh";
import { OnSaveValidationJob } from "./definitions/on-save-validation";
import { EntryDeleteCleanupJob } from "./definitions/entry-delete-cleanup";
import { SyncStateFlushJob } from "./definitions/sync-state-flush";
import { BindingPropagationJob } from "./definitions/binding-propagation";
import { ClusterHubPathRewriteJob } from "./definitions/cluster-hub-path-rewrite";
import { AiImageGcJob } from "./definitions/ai-image-gc";
import { SeoIndexRefreshJob } from "./definitions/seo-index-refresh";
import { EventWebhookDeliveryJob } from "./definitions/event-webhook-delivery";
import { DraftLinkCheckJob, ProposalStaleSweepJob } from "./definitions/proposal-maintenance";
import { MetaAdsSyncJob } from "./definitions/meta-ads-sync";
import { AdsSyncJob } from "./definitions/ads-sync";
import { AdsRecheckJob } from "./definitions/ads-recheck";
import { HtmlPageRebuildJob } from "./definitions/html-page-rebuild";
import { HtmlDbReaderRebuildJob } from "./definitions/html-db-reader-rebuild";
import { HtmlContentTypeListingRebuildJob } from "./definitions/html-content-type-listing-rebuild";
import { HtmlContentTypeRebuildJob } from "./definitions/html-content-type-rebuild";
import { LocalDatabaseRefreshJob } from "./definitions/local-database-refresh";

export function registerAllJobs(): void {
  registerJobClass("index_refresh", IndexRefreshJob);
  registerJobClass("on_save_validation", OnSaveValidationJob);
  registerJobClass("entry_delete_cleanup", EntryDeleteCleanupJob);
  registerJobClass("sync_state_flush", SyncStateFlushJob);
  registerJobClass("binding_propagation", BindingPropagationJob);
  registerJobClass("cluster_hub_path_rewrite", ClusterHubPathRewriteJob);
  registerJobClass("ai_image_gc", AiImageGcJob);
  registerJobClass("seo_index_refresh", SeoIndexRefreshJob);
  registerJobClass("event_webhook_delivery", EventWebhookDeliveryJob);
  registerJobClass("proposal_stale_sweep", ProposalStaleSweepJob);
  registerJobClass("draft_link_check", DraftLinkCheckJob);
  registerJobClass("ads_sync", AdsSyncJob);
  registerJobClass("ads_recheck", AdsRecheckJob);
  registerJobClass("meta_ads_sync", MetaAdsSyncJob);
  registerJobClass("html_page_rebuild", HtmlPageRebuildJob);
  registerJobClass("html_db_reader_rebuild", HtmlDbReaderRebuildJob);
  registerJobClass("html_content_type_listing_rebuild", HtmlContentTypeListingRebuildJob);
  registerJobClass("html_content_type_rebuild", HtmlContentTypeRebuildJob);
  registerJobClass("local_database_refresh", LocalDatabaseRefreshJob);
}
