import path from "path";
import { getPackageRoot, getProjectRoot, isProductionMode, resetPathCaches } from "../../shared/paths.js";
import { detectProject } from "./detect.js";
import { askAgentChoice, askText, askYesNo, canPrompt } from "./prompts.js";
import type { CliFlags, ResolvedConfig } from "./types.js";

function slugify(name: string): string {
  return name
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "")
    .slice(0, 48) || "site";
}

/**
 * Precedence: flags > answers > defaults > refuse.
 */
export async function resolveConfig(flags: CliFlags): Promise<ResolvedConfig> {
  resetPathCaches();
  if (flags.production) {
    process.env.NODE_ENV = "production";
  }

  const projectRoot = getProjectRoot();
  const packageRoot = getPackageRoot();
  const isProduction = isProductionMode(process.argv) || flags.production;
  const detect = detectProject(projectRoot);

  let displayName = flags.name;
  let contentSlug = flags.slug;
  let wantAgent = false;
  let agentChoice = flags.agent ?? null;

  if (detect.kind === "empty" && !isProduction) {
    if (!displayName) {
      if (!canPrompt() && !flags.yes) {
        throw new Error("Creating a site requires --name (or an interactive terminal).");
      }
      displayName = canPrompt()
        ? await askText("Site display name", "My Site")
        : "My Site";
    }
    if (!contentSlug) {
      contentSlug = slugify(displayName);
      if (canPrompt() && !flags.slug) {
        contentSlug = (await askText("Content folder slug (site_<slug>)", contentSlug)) || contentSlug;
      }
    }
    contentSlug = contentSlug.replace(/^site_/, "");
  }

  if (detect.kind === "empty" && isProduction) {
    throw new Error(
      "Production mode will not create a new site on the server. Create the project locally, then deploy the folder.",
    );
  }

  if (detect.kind === "dirty") {
    throw new Error((detect.issues ?? ["Invalid project directory"]).join("\n"));
  }

  const skipInteractive =
    isProduction || (!canPrompt() && detect.kind === "project");

  // Agent prompts only for bare `npx weblify` (start site). Skip for commands like `token`.
  if (!isProduction && detect.kind !== "dirty" && !flags.command) {
    if (flags.agenticInstallation) {
      wantAgent = true;
    } else if (skipInteractive) {
      wantAgent = false;
    } else if (canPrompt()) {
      wantAgent = await askYesNo(
        "Want an agent (Cursor / Claude Code / Claude.ai) to help install and configure this site?",
        true,
      );
    }

    if (wantAgent && !agentChoice) {
      if (flags.noMcpTunnel) {
        agentChoice = "local";
      } else if (canPrompt()) {
        agentChoice = await askAgentChoice();
      } else {
        agentChoice = "local";
      }
    }
  }

  if (isProduction && flags.agenticInstallation) {
    console.warn("Ignoring --agentic-installation in production (dev-only).");
  }

  return {
    projectRoot,
    packageRoot,
    isProduction,
    detect,
    displayName,
    contentSlug,
    wantAgent: wantAgent && !isProduction,
    agentChoice: isProduction ? null : agentChoice,
    noMcpTunnel: flags.noMcpTunnel,
    command: flags.command,
  };
}

export function contentFolderName(slug: string): string {
  return slug.startsWith("site_") ? slug : `site_${slug}`;
}

export function sitesYmlForLocalhost(contentFolder: string): string {
  return `# Generated by weblify CLI
localhost:
  content_folder: ${contentFolder}
`;
}

export function projectGitignore(): string {
  return `.env
.env.local
data/
.cache/
.local/
node_modules/
`;
}

export { path };
